### PR TITLE
I added the support for the page to take up the full screen

### PR DESCRIPTION
**Pull request by Dirius77**
...scales based on the size of the page and the font that the person is using. This does cause buttons to sometimes only take up about half of the button bar, but I think that looks better than forcing them to take up the entire space (Which looked just plain awful on my screen)

### CODE REVIEW

**Comment by dantheman629** [comment]
great thank you I'll take a look at it.

**Comment by dantheman629** [comment]
hey so it's getting closer but it's still not exactly what I'm hoping for.  Couple notes. 

 First when I resize the window the display div doesn't resize properly.  I believe that's due to the fact that it has a scroll bar attached to it that you don't take into account for while resizing.

Second the heights don't resize at all which is not good,  I need both dimensions to alter their size.

Finally,  I totally get the whole don't resize the buttons thing.  I agree that If they grew to take up their whole space it would look bad.  On the other hand, they do need to do something besides just stack up on the left.  If the window shrinks at all they just get covered up, and if the window gets too big the buttons don't even center or spread themselves out.  May i suggest that the button window has a set ratio of dimensions, like the height is half it's width, and the text/button sizes can then grow and shrink to max size without looking weird.  Then the info/display divs share the rest of the height at a set ratio?

**Comment by Dirius77** [comment]
The thing with the buttons would probably be javascript, and programming the heights to scale should be easier, I'll fiddle with it and see if I can fix it

**Comment by dantheman629** [comment]
yeah i thought so.  All help with the ui is appreciated, feel free to help as much as you want.  Anything you don't do I'll get around to eventually, but the auto sizing ui is low on the priority list right now

**Comment by Dirius77** [comment]
I might as well work on something you're not doing currently though if I want to help. I'd also ask what you suggest it should do with the buttons when the screen is simply not large enough to fit them all within a button box? (such as an ipod screen)

**Comment by dantheman629** [comment]
Shrink the text/buttons.

**Comment by Dirius77** [comment]
But to shrink them that much would they really be able to use the buttons or read the text?

**Comment by dantheman629** [comment]
Well for now, theres always going to be 15 buttons.  That can be revisited later but for now it's true.  So i suggest we see what happens if we shrink the buttons/text and go from there.  If you have any questions about the javascript please ask.  I suggest you make your edits in displayUi.js or buttonUi.js.  Also you should do your edits on a fresh pull because i merged someone elses auto resize which was working pretty well

**Comment by Dirius77** [comment]
Alright I'll move to that.

**Pull request closed without merging**
